### ISSUE TITLE
Links between docs

### ISSUE THREAD

**Issue by jonathan-irvin** [learnroku/crash-course#6]
Hey @timbeynart-nbcuni I'm running through your crash course (as I just started working as a Roku Dev) and things are going well.  Your documents are well-laid out and descriptive.  One bit of feedback I had (and it's really small) was to create links between your different lessons.  Having a link to Lesson 3 at the end of Lesson 2 would be super helpful once you complete each one.

Also, is there a way I can tip you or something?  I know that was probably not your idea with this tutorial, but I like to give back.

I did create a little something to help automate sideloading using NodeJS.  Maybe we can include that in the lesson to ease the burden of making small changes and having to upload each one.

One lesson I did learn in this was you can't just zip up a directory, you have to zip the contents of the directory and them upload it.

Either way, I'm just starting lesson 3 and I'm very grateful this is around.

**Comment by timbeynart-nbcuni** [comment]
Thanks for reaching out. I don't really maintain this tutorial any more, I moved from Roku to server-side API development, so any feedback helps! 
If you like, you can create links as you go through this and add a pull request. I'll merge it in to the project. Otherwise I'll try to make time to update it.
For launching, I used the Atom editor and sideloaded using a package called `roku-develop`. It is a major help.
As for a tip, don't worry about it.  This tutorial was my way of giving back.

Good luck with Roku! It's a challenge.
Tim

**Comment by timbeynart-nbcuni** [comment]
I think I fixed this.
